import Head from "next/head"
import Image from "next/image"
import { ethers } from "ethers"
import { useEffect, useState } from "react"
import Header from "../components/Header"
import MainHeader from "../components/MainHeader"
import LotteryEntrance from "../components/LotteryEntrance"

export default function Home() {
    return (
        <div>
            <Head>
                <title>Smart Contract Lottery </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/* <Header /> */}
            <MainHeader />
            <LotteryEntrance />
        </div>
    )
}
